apiVersion: v1
data:
  vlc-nox-k8s.conf: |
    URL=/data/sample.avi
    TRANSCODE="#transcode{vcodec=mjpg,vb=2500,scale=1.0,fps=10,acodec=none}:standard{access=http{mime=multipart/x-mixed-replace;boundary=7b3cc56e5f51db803f790dad720ed50a},mux=mpjpeg,dst=:8888/videostream}"
kind: ConfigMap
metadata:
  name: vlc-config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vc
    spec:
       containers:
       - name: vc-ssh
         image: besn0847/videocontroller:vc-ssh
         imagePullPolicy: IfNotPresent 
         ports:
           - containerPort: 22
         volumeMounts:
         - name: conf-persistent-storage
           mountPath: /conf
         - name: data-persistent-storage
           mountPath: /data
       - name: vc-plex
         image: besn0847/videocontroller:vc-plex
         imagePullPolicy: IfNotPresent 
         ports:
           - containerPort: 32400
         volumeMounts:
         - name: conf-persistent-storage
           mountPath: /conf
         - name: data-persistent-storage
           mountPath: /data
       - name: vc-vlc
         image: besn0847/videocontroller:vc-vlc
         imagePullPolicy: IfNotPresent 
         ports:
           - containerPort: 8888
         volumeMounts:
         - name: conf-persistent-storage
           mountPath: /conf
         - name: data-persistent-storage
           mountPath: /data
         - name: vlc-config
           mountPath: /conf/k8s
       - name: vc-motion
         image: besn0847/videocontroller:vc-motion
         imagePullPolicy: IfNotPresent 
         ports:
           - containerPort: 8080
           - containerPort: 8081
         volumeMounts:
         - name: conf-persistent-storage
           mountPath: /conf
         - name: data-persistent-storage
           mountPath: /data
       - name: vc-nodered
         image: besn0847/videocontroller:vc-nodered
         imagePullPolicy: IfNotPresent 
         ports:
           - containerPort: 1880
         volumeMounts:
         - name: conf-persistent-storage
           mountPath: /conf
         - name: data-persistent-storage
           mountPath: /data
       volumes:
       - name: conf-persistent-storage
         emptyDir: {}
       - name: data-persistent-storage
         emptyDir: {}
       - name: vlc-config
         configMap:
           name: vlc-config
---
apiVersion: v1
kind: Service
metadata:
  name: svc-vc
  labels:
    run : vc
spec:
  selector:
    app: vc
  type: NodePort
  ports:
   - name: port30022
     protocol: TCP
     port: 22
     nodePort: 30022
   - name: port32400
     protocol: TCP
     port: 32400
     nodePort: 30000
   - name: port8081
     protocol: TCP
     port: 8081
     nodePort: 30081
