apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vc
    spec:
       containers:
       - name: vc-ftpd
         image: besn0847/videcontroller:vc-ftpd
         ports:
           - containerPort: 20
           - containerPort: 21
         volumeMounts:
         - name: conf-persistent-storage
           mountPath: /conf
         - name: data-persistent-storage
           mountPath: /data
       - name: vc-plex
         image: besn0847/videcontroller:vc-plex
         ports:
           - containerPort: 32400
         volumeMounts:
         - name: conf-persistent-storage
           mountPath: /conf
         - name: data-persistent-storage
           mountPath: /data
       - name: vc-vlc
         image: besn0847/videcontroller:vc-vlc
         ports:
           - containerPort: 8888
         volumeMounts:
         - name: conf-persistent-storage
           mountPath: /conf
         - name: data-persistent-storage
           mountPath: /data
       - name: vc-motion
         image: besn0847/videcontroller:vc-motion
         ports:
           - containerPort: 8081
         volumeMounts:
         - name: conf-persistent-storage
           mountPath: /conf
         - name: data-persistent-storage
           mountPath: /data
       volumes:
       - name: conf-persistent-storage
         emptyDir: {}
       - name: data-persistent-storage
         emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-vc
  labels:
    run : vc
spec:
  selector:
    app: vc
  type: NodePort
  ports:
   - name: port20
     protocol: TCP
     port: 20
     nodePort: 30020
   - name: port21
     protocol: TCP
     port: 21
     nodePort: 30021
   - name: port32400
     protocol: TCP
     port: 32400
     nodePort: 30000
   - name: port8081
     protocol: TCP
     port: 8081
     nodePort: 30081
   - name: port8888
     protocol: TCP
     port: 8888
     nodePort: 30088
